name: elastic_app_search
description: Dart/Flutter package for using Elastic App Search through a simple API returning easy to handle objects
version: 0.4.3
repository: https://github.com/julienlebren/elastic_app_search
issue_tracker: https://github.com/julienlebren/elastic_app_search/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.4
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter: